
development:
  adapter: postgresql
  encoding: unicode
  database: yoda_advice_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: yoda_advice_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: yoda_advice_production
  pool: 5
